// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using teploobmen.Data;

#nullable disable

namespace teploobmen.Migrations
{
    [DbContext(typeof(MyApplicationContext))]
    [Migration("20231122045343_TableInputDatas")]
    partial class TableInputDatas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("teploobmen.Data.InputData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("M")
                        .HasColumnType("REAL");

                    b.Property<float>("RasD")
                        .HasColumnType("REAL");

                    b.Property<int>("RasH")
                        .HasColumnType("INTEGER");

                    b.Property<float>("RasRas")
                        .HasColumnType("REAL");

                    b.Property<float>("RasTemG")
                        .HasColumnType("REAL");

                    b.Property<float>("RasTemM")
                        .HasColumnType("REAL");

                    b.Property<int>("RasTepl")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RasTg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RasTm")
                        .HasColumnType("INTEGER");

                    b.Property<float>("RasV")
                        .HasColumnType("REAL");

                    b.Property<float>("Y0")
                        .HasColumnType("REAL");

                    b.Property<float>("Y1")
                        .HasColumnType("REAL");

                    b.Property<float>("Y1_DOP")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("InputDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
